(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var u3=function(a){a.ea("cardstatechange",a.Eh()&&a.Bk()?1:0)},v3=function(a,b){var c=g.La(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},dSa=function(a){var b=g.mn(a);
a=g.sn(a);return new g.Zm(b.x,b.y,a.width,a.height)},eSa=function(a){return Math.pow(a,3)},fSa=function(a){return 3*a*a-2*a*a*a},y3=function(a){a=g.Pa(a);
delete w3[a];g.Pe(w3)&&x3&&x3.stop()},hSa=function(){x3||(x3=new g.L(function(){gSa()},20));
var a=x3;a.isActive()||a.start()},gSa=function(){var a=g.Ra();
g.ze(w3,function(b){iSa(b,a)});
g.Pe(w3)||hSa()},z3=function(a,b,c,d){g.xs.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.K=0;this.D=null},iSa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;jSa(a,a.progress);1==a.progress?(a.i=0,y3(a),a.onFinish(),a.Lw()):a.Hc()&&a.qC()},jSa=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},kSa=function(a,b){g.re.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.i},A3=function(a,b,c,d,e){z3.call(this,b,c,d,e);
this.element=a},B3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
A3.call(this,a,b,c,d,e)},C3=function(a){g.G.call(this);
this.u=a||window;this.i=[]},D3=function(a){return a.baseUrl||null},E3=function(a,b){return g.hq(g.Vn(a,b,void 0),function(c){return!!c})},lSa=function(a,b,c){function d(Y){var ya,Na,lb,ib=Y.hovercardButton;
if(!ib)return null;ib=ib.subscribeButtonRenderer;if(!ib)return null;var yb=f(ib.unsubscribedButtonText),mc=f(ib.subscribedButtonText);if(ib.subscribed){var Ta=f(ib.subscriberCountWithUnsubscribeText);var bd=f(ib.subscriberCountText)}else Ta=f(ib.subscriberCountText),bd=f(ib.subscriberCountWithSubscribeText);var ub=null;return Y.signinEndpoint&&(ub=v3(Y,"signinEndpoint","webNavigationEndpointData","url"),ub||(ub=null===(lb=null===(Na=null===(ya=ib.signInEndpoint)||void 0===ya?void 0:ya.commandMetadata)||
void 0===Na?void 0:Na.webCommandMetadata)||void 0===lb?void 0:lb.url),!ub)?null:yb&&(mc||ub)?{subscribed:ib.subscribed,subscribeText:yb,subscribeCount:Ta,unsubscribeText:mc,unsubscribeCount:bd,enabled:ib.enabled,signinUrl:ub,classic:Y.useClassicSubscribeButton}:null}
function e(Y){if(Y){var ya=[],Na=Y.videoId;Na&&ya.push("v="+Na);(Na=Y.playlistId)&&ya.push("list="+Na);(Y=Y.startTimeSeconds)&&ya.push("t="+Y);return"/watch?"+ya.join("&")}}
function f(Y){if(!Y)return null;var ya=Y.simpleText;return ya?ya:Y.runs?g.Vn(Y.runs,function(Na){return Na.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,u=null,x=!1,y=null,z=null,D=null,H=null,F=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=v3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):z=f(b.subscribersText)}else"WEBSITE"===
h?((D=v3(l,"urlEndpoint","url"))&&(m=D),n=!0,p="new",D=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(F=f(b.additionalFeesText)),(n=v3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=v3(b,"title","accessibility","accessibilityData","label");var K=b.endpoint?b.endpoint.clickTrackingParams:null,W="";if(b.metadata){var J=f(b.metadata);J&&(W=J)}return{id:"element-"+c,type:h,title:f(b.title),metadata:W,callToAction:f(b.callToAction),lK:b.image,
iconUrl:D,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:z,isSubscribe:x,targetUrl:m||null,oT:n,sessionData:K?{itct:K}:null,WX:p,Pu:a?a:null,rT:b.isPlaceholder,impressionUrls:E3(b.impressionUrls||[],D3),hT:E3(b.hovercardShowUrls||[],D3),clickUrls:E3(l.loggingUrls||[],D3),visualElement:g.py(b.trackingParams),
productPrice:H,additionalFeesText:F}},F3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:E3(a.impressionUrls||[],D3),elements:E3(a.elements||[],function(d,e){return lSa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.py(a.trackingParams));return c},G3=function(a){g.EM.call(this,a);
this.B=this.endscreen=null;this.i={};this.D={};this.C=this.u=null;this.K=[];this.X=!0;this.I=0;a=a.V();this.S=g.tE(a)||g.xE(a);this.events=new g.LC(this);g.I(this,this.events);this.events.T(this.player,g.tz("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.uz("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.yb);this.events.T(window,"focus",this.ZW);this.load();var b=g.ih("STYLE");(g.Vg("HEAD")[0]||document.body).appendChild(b);g.qe(this,function(){g.mh(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},mSa=function(a){return a.player.getVideoData().D?"current":a.S?"new":"current"},H3=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},nSa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=F3(f,mSa(a))));I3(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.Gq;d&&(c.postParams={ad_tracking:d});if(b=g.Osa(b))if(b=g.Tf(b),b=g.Pf(b))a.B=g.Du(b,c)},I3=function(a,b,c){c=void 0===c?!0:c;
a.player.Ze("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&oSa(a);c=[];d=new g.rz(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.V({G:"div",L:"ytp-ce-shadow"}),g.rM(a.player,a.u.element,4),a.C=new g.XK(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=pSa(a,e);if(f){a.i[e.id]=f;a.D[e.id]=e;g.rM(a.player,f.element,4);var h=new g.rz(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);qSa(a,
f,e)}else g.Cy(new g.yw("buildEndscreenElement null",e))}a.player.Gd(c);a.yb()}},oSa=function(a){var b=g.sy(),c=g.ty();
c&&b&&a.endscreen.visualElement&&g.Gy(void 0,c,b,[a.endscreen.visualElement])},pSa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ja:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.Pu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:J3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:K3(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ja:["ytp-ce-video-title"].concat(g.v(c)),W:{dir:g.Cs(b.title||
"")},va:b.title},{G:"div",L:"ytp-ce-video-duration",va:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ja:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.Pu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:J3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:K3(a,
b.targetUrl),tabindex:"-1"},U:[{G:"div",Ja:["ytp-ce-playlist-title"].concat(g.v(c)),W:{dir:g.Cs(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-playlist-count",U:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={G:"div",Ja:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.Pu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"a",Ja:["ytp-ce-channel-title","ytp-ce-link"],W:{href:K3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Cs(b.title||"")},va:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",U:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{G:"div",Ja:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:J3(b)}]};c=new g.V(c);var d=g.Wg(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.M(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.HN(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ja:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.Pu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-website-title",W:{dir:g.Cs(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-website-metadata",va:b.metadata},{G:"a",Ja:["ytp-ce-website-goto","ytp-ce-link"],W:{href:K3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:J3(b)},{G:"div",
L:"ytp-ce-expanding-icon",W:rSa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",U:[{G:"div",L:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.U.push({G:"div",L:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={G:"div",Ja:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.Pu||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-merchandise-title",W:{dir:g.Cs(b.title||"")},va:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",va:b.metadata},{G:"a",Ja:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:K3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",W:J3(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",U:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",va:b.callToAction||void 0}]}]},c=new g.V(a)}b.rT&&g.M(c.element,"ytp-ce-placeholder");return c},J3=function(a){if(a.lK)var b=a.lK.thumbnails;
return rSa(b?b[b.length-1].url:null)},rSa=function(a){return a?{style:"background-image: url("+a+")"}:{}},qSa=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.X&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.M(b.element,"ytp-ce-force-expand"),L3(a,c.id,!0)):(g.ns(b.element,"ytp-ce-force-expand"),g.ns(b.element,"ytp-ce-element-hover"),L3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){M3(a,b,c)});
b.Ra("mouseleave",function(){N3(a,b,c)});
a.player.V().isMobile||b.Ra("click",function(){g.M(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){sSa(a,c,m)});
b.Ra("keypress",function(m){sSa(a,c,m)});
b.Ra("focus",function(){M3(a,b,c)});
b.Ra("blur",function(){N3(a,b,c)});
b.Ra("touchstart",function(){M3(a,b,c)});
var l=g.Yg("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.ns(b.element,"ytp-ce-element-hover");g.ns(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.X=9===m.keyCode&&!m.shiftKey});
d(g.Yg("ytp-sb-subscribe",b.element));d(g.Yg("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},sSa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.ls(d,"ytp-ce-element");){g.ls(d,"subscribe-label")&&O3(a,b);
if(g.ls(d,"ytp-ce-channel-subscribe"))return;d=g.nh(d)}if(!d||g.ls(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])N3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.WX)O3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Tf(K3(a,b.targetUrl)),c=g.Pf(c),g.wL(c,void 0,b.sessionData);else{var e=a.player.getVideoData().D,f=function(){var h=K3(a,b.targetUrl),l=b.sessionData,m=g.iu(h);e&&m&&(m.v||m.list)?a.player.Wj(m.v,l,m.list,!1):
g.vL(h,l)};
O3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},K3=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.VE(a)+b}else return"";return b},M3=function(a,b,c){g.ls(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.M(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.L(function(){g.M(b.element,"ytp-ce-element-hover")},200)).start():g.M(b.element,"ytp-ce-element-hover"),P3(a,c.hT),L3(a,c.id,!0))},N3=function(a,b,c){g.ns(b.element,"ytp-ce-element-hover");
g.ns(b.element,"ytp-ce-force-expand");L3(a,c.id,!1)},L3=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.i[e].element,"ytp-ce-element-shadow-show",c)},P3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||H3(a))c&&c();else{b=tSa(a,b);var e=0,f=!1,h=new g.L(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Gv(b[a],d)}},O3=function(a,b,c){P3(a,b.clickUrls,c);
(a=g.ty())&&b.oT&&g.My(a,b.visualElement)},tSa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(uSa(b[d],c));return a},uSa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},vSa=function(a){return"string"===typeof a?a:""},Q3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},wSa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},R3=function(a){return a.value?a.value:null},S3=function(a){if(!a)return null;
var b=g.Tf(vSa(a.value));b=g.Pf(b);if(!b)return null;var c=Q3(a.target,xSa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new wSa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},ySa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},BSa=function(a){if(!a)return null;
var b=Q3(a.type,zSa),c=Q3(a.trigger,ASa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=S3(a?a:null);return b?new ySa(b,c,a):null},CSa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},ESa=function(a){return(a=DSa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},DSa=function(a,b){return g.Rb(a.action,b,void 0)},FSa=function(a,b){this.context=a;
this.i=b},U3=function(a){return a.customMessage?T3("div","iv-card-message",a.customMessage):""},V3=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",W:{style:a},U:c}},W3=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(T3("li","",c.value));return{G:"ul",L:"iv-card-meta-info",U:b}},T3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Cs(c);return{G:a,W:b,va:c}},GSa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Ay&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Ay+");");c.dir=g.Cs(a.customMessage);var d=[{G:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ja:b,W:c,U:d}},X3=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},HSa=function(a,b){this.merchant=a;
this.price=b},ISa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},JSa=function(a,b){return b?b:ISa(a)?"current":"new"},Y3=function(a,b){g.G.call(this);
var c=this;this.element=a;this.context=b;this.eb=!1;this.Sa=new Map;this.Va=new Map;this.context.J.addEventListener(g.tz("annotations_module"),function(d){(d=c.Sa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.uz("annotations_module"),function(d){(d=c.Va.get(d))&&d.apply(c)})},Z3=function(a,b,c,d,e,f,h){a.context.i.Ra(b,"click",function(l){a.rC(c,d,e,f||[],h||0,l)});
a.context.i.Ra(b,"touchstart",function(){a.eb=!1});
a.context.i.Ra(b,"touchmove",function(){a.eb=!0})},KSa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},$3=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
vO:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
sB:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},c4=function(a,b,c){Y3.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Ka=this.rb=this.B=this.isInitialized=!1;this.xa=null;this.cards=[];this.ob=this.S=this.Ia=this.D=this.La=this.i=null;this.Z=[];this.K=this.Ge=this.Ba=null;this.I=0;this.Aa=new g.L(g.Ia,c.Y.Yd?4E3:3E3);g.I(this,this.Aa);this.Za=new g.L(g.Ia);g.I(this,this.Za);this.oa=new FSa(c,function(e,f,h,l,m,n){Z3(d,e,f,h,l,m,n)});
this.X=new g.V({G:"div",L:"iv-drawer",W:{id:"iv-drawer"},U:[{G:"div",L:"iv-drawer-header",W:{"aria-role":"heading"},U:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ja:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.I(this,this.X);this.C=this.X.element;this.Wa=new g.XK(this.X,330);g.I(this,this.Wa);this.jb=g.Yg("iv-drawer-header-text",this.C);this.u=g.Yg("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.rb&&a4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.rb=d.B)&&b4(d)})},LSa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){a4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){b4(a)});
var c=b.headerText;g.ph(a.jb,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ba=g.py(b.trackingParams);a.K=g.py(b.closeTrackingParams);a.Ge=g.py(b.iconTrackingParams)},MSa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.yz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.command),Ol:d.trackingParams?g.py(d.trackingParams):null,bj:e.trackingParams?
g.py(e.trackingParams):null,Ge:f&&f.trackingParams?g.py(f.trackingParams):null,imageUrl:e4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.yz(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Ay:null,title:d.title?g.yz(d.title):"",customMessage:d.callToAction?g.yz(d.callToAction):"",url:d.command.urlEndpoint.url?S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};f4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.yz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.endpoint),Ol:d.trackingParams?g.py(d.trackingParams):null,bj:e.trackingParams?g.py(e.trackingParams):null,Ge:f&&f.trackingParams?
g.py(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.yz(d.customText):null,profileImageUrl:e4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.yz(d.channelName):"",metaInfo:[d.subscriberCountText?g.yz(d.subscriberCountText):""],url:S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
f4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.yz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.action),Ol:d.trackingParams?g.py(d.trackingParams):
null,bj:e.trackingParams?g.py(e.trackingParams):null,Ge:f&&f.trackingParams?g.py(f.trackingParams):null,Hx:e4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.yz(d.customMessage):null,playlistVideoCount:g.yz(d.playlistVideoCount),title:d.playlistTitle?g.yz(d.playlistTitle):"",metaInfo:[d.channelName?g.yz(d.channelName):"",d.videoCountText?g.yz(d.videoCountText):""],url:S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:KSa(d.action)})};f4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.yz(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:d4(a,c,b,d),sponsored:!1,tracking:$3(d,e,d.action),Ol:d.trackingParams?g.py(d.trackingParams):null,bj:e.trackingParams?g.py(e.trackingParams):null,Ge:f&&f.trackingParams?g.py(f.trackingParams):
null,Hx:e4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.yz(d.lengthString):null,customMessage:d.customMessage?g.yz(d.customMessage):null,title:d.videoTitle?g.yz(d.videoTitle):"",metaInfo:[d.channelName?g.yz(d.channelName):"",d.viewCountText?g.yz(d.viewCountText):""],isLiveNow:!!d.badge,url:S3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:KSa(d.action)})};f4(a,b)}a.I++},e4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},d4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},OSa=function(a,b){if(b=NSa(a,b))b===a.i&&(a.i=null),a.J.removeCueRange(b.card.id),g.mh(b.pD),g.Zb(a.cards,b),a.Cy(),g4(a)},a4=function(a,b,c){if(!a.B){a.Wa.show();
a.La=new g.L(function(){g.M(a.context.J.getRootNode(),g.gT.IV_DRAWER_OPEN)},0);
a.La.start();a.xa=g.pv(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.ty();d&&a.Ba&&a.K&&g.Ky(d,[a.Ba,a.K]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.VL||(f.VL=!0,PSa(a.context.logger,f.card.tracking.impression,b)),d&&g.Ky(d,[f.card.Ol]);u3(a.J);c&&(a.D=new g.L(function(){a.Ia=a.S;a.ob.focus()},330),a.D.start())}},b4=function(a){a.B&&(a.Wa.hide(),g.qv(a.xa),a.xa=null,g.ns(a.context.J.getRootNode(),g.gT.IV_DRAWER_OPEN),a.B=!1,u3(a.J),a.D&&a.D.stop(),a.D=new g.L(function(){a.Ia&&(a.Ia.focus(),a.Ia=null)},330),a.D.start())},
RSa=function(a){g.ms(a.element,[g.gT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.rM(a.J,a.C,5);QSa(a);a.S=g.Yg("ytp-cards-button",a.J.getRootNode());a.ob=g.Yg("iv-drawer-close-button",a.C);a.isInitialized=!0},QSa=function(a){var b=g.Yg("iv-drawer-close-button",a.C);
a.context.i.Ra(b,"click",a.RR,a);a.context.i.Ra(a.u,"touchend",function(){a.Aa.start()});
a.context.i.Ra(a.u,"scroll",a.dS,a);a.context.u.subscribe("onHideControls",function(){a.Ka=!0});
a.context.u.subscribe("onShowControls",function(){a.Ka=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ka=g.ls(a.J.getRootNode(),"ytp-autohide")});
a.Z.push(g.Mv("iv-button-shown",a.wT,a));a.Z.push(g.Mv("iv-button-hidden",a.vT,a));a.Z.push(g.Mv("iv-teaser-shown",a.BQ,a));a.Z.push(g.Mv("iv-teaser-hidden",a.xT,a));a.Z.push(g.Mv("iv-teaser-clicked",a.AQ,a))},f4=function(a,b){a.isInitialized||RSa(a);
OSa(a,b.id);var c=SSa(a,b);if(c){var d={card:b,pD:c.element,VL:!1},e=TSa(a,d);g.ec(a.cards,e,0,d);c.Ea(a.u,e);a.Cy();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.i=d,g4(a),USa(a,d),a4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&VSa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){VSa(a,d)}),g4(a))}},SSa=function(a,b){switch(b.type){case "simple":a=a.oa;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",va:b.displayDomain}:void 0;var d=GSa(b);c={G:"div",Ja:["iv-card"],U:[{G:"a",L:"iv-click-target",W:{href:b.url?R3(b.url)||"":""},U:[V3(b.imageUrl,c),{G:"div",L:"iv-card-content",U:[T3("h2",void 0,b.title),d]}]}]};c=new g.V(c);X3(a,g.Xg("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.oa,c={G:"div",Ja:["iv-card","iv-card-channel"],U:[{G:"a",Ja:["iv-click-target"],W:{href:R3(b.url)||"","data-ytid":b.channelId},U:[V3(b.profileImageUrl),
{G:"div",L:"iv-card-content",U:[U3(b),{G:"h2",L:"iv-card-primary-link",va:b.title},W3(b)]}]}]},c=new g.V(c),X3(a,g.Xg("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.oa,c={G:"div",Ja:["iv-card","iv-card-playlist"],U:[{G:"a",L:"iv-click-target",W:{href:R3(b.url)||""},U:[V3(b.Hx,{G:"div",L:"iv-card-image-overlay",U:[{G:"span",L:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",U:[U3(b),T3("h2","iv-card-primary-link",b.title),W3(b)]}]}]},c=new g.V(c),
X3(a,g.Xg("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.oa;var e=!g.Wb(b.offers);c=["iv-card"];d="";var f=GSa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",va:f.merchant}),f={G:"div",U:e});e=b.url?R3(b.url)||"":"";c={G:"div",Ja:c,W:{tabindex:"0"},U:[{G:"a",Ja:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",U:[b.sponsored?{G:"div",L:"iv-card-sponsored",U:["Sponsored",{G:"div",L:"iv-ad-info-container",U:[{G:"div",L:"iv-ad-info",va:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",U:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",W:{href:e},U:[T3("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.ih("span");g.ph(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.rd(d,"adInfo");X3(a,g.Xg("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.oa,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",va:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ja:["yt-badge","yt-badge-live"],va:"LIVE NOW"}:null,e={G:"div",Ja:["iv-card","iv-card-video"],U:[{G:"a",L:"iv-click-target",W:{href:(null===(c=b.url)||void 0===c?void 0:R3(c))||""},U:[V3(b.Hx,d),{G:"div",L:"iv-card-content",U:[U3(b),T3("h2","iv-card-primary-link",b.title),W3(b),f]}]}]},c=new g.V(e),
X3(a,g.Xg("iv-click-target",c.element),b,b.url),c;default:return null}},TSa=function(a,b){if(0===a.cards.length)return 0;
a=g.Sb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},WSa=function(a){return a.i?"productListing"===a.i.card.type:g.Wn(a.cards,function(b){return"productListing"===b.card.type})},g4=function(a){g.N(a.J.getRootNode(),"ytp-cards-shopping-active",WSa(a))},VSa=function(a,b){if(!g.ls(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.ty(),d=a.i?a.i.card.Ge:a.Ge;
c&&d&&g.Ly(c,[d]);a.i=b;g4(a)}if(c="none"!=a.element.style.display)a.context.J.V().N("html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.J.getPresentingPlayerType()?(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.J.getAdState();c&&b.card.teaserDurationMs&&a.J.Jt(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Za.isActive()||((!a.B||!a.Aa.isActive()&&a.Ka)&&USa(a,b),a.Za.start(910+b.card.teaserDurationMs))}},
USa=function(a,b){a.X.wb?(b=new z3([0,
a.u.scrollTop],[0,b.pD.offsetTop],600,fSa),a.context.B.Ra(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ra(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.nK(a.X,!0),a.u.scrollTop=b.pD.offsetTop,g.nK(a.X,!1))},h4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},NSa=function(a,b){return g.Rb(a.cards,function(c){return c.card.id===b})},i4=function(a,b,c){Y3.call(this,a,b);
this.annotation=c;this.isActive=!1},XSa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},j4=function(a,b,c){i4.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.i=this.I=this.D=null},YSa=function(a,b){var c=void 0===c?0:c;
var d=dSa(b).width;g.kn(b,d);c=new B3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,eSa);g.I(a,c);a.context.B.Ra(c,"begin",function(){g.In(b,!0)});
c.play()},aTa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ja:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({G:"div",Ja:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.HN(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.J),a.i.Ea(d));var f=a.createElement({G:"div",Ja:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ja:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.In(h,!1);var l=a.createElement({G:"div",Ja:["branding-context-container-outer"]});l.appendChild(h);g.cn(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.L(function(){ZSa(a,h,l)},500);
g.I(a,a.B);a.context.i.Ra(a.element,"mouseover",function(){$Sa(a,h,l,f,b.image_height)});
a.context.i.Ra(a.element,"mouseout",function(){a.B.start()})}},$Sa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.sn(b);a.i||(b.style.width=g.jn(f.width,!0),c.style.width=g.jn(f.width,!0));g.cn(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.cn(d,"right","1px");a.C=!0;g.In(b,!0);a.D=new g.L(function(){g.M(this.element,"iv-branding-active")},0,a);
a.D.start()}},ZSa=function(a,b,c){g.ns(a.element,"iv-branding-active");
a.I=new g.L(function(){g.In(b,!1);a.i||(c.style.width=g.jn(0,!0))},250);
a.I.start();a.C=!1},bTa=function(a,b,c,d,e,f,h){this.i=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.J=f;this.u=h},k4=function(a,b,c){i4.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.X=!1;this.I=5E3;this.u=this.B=this.i=this.C=null;this.K=this.createElement({G:"div",Ja:["iv-promo-contents"]});this.D=new g.L(function(){d.i.setAttribute("aria-hidden","true");g.In(d.B,!1);g.In(d.u,!0)},700,this);
g.I(this,this.D)},cTa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=ESa(a.annotation),f=b.image_url;if(f){var h=a.createElement({G:"div",Ja:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&Z3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.pg(f,R3(e)),a.i=f):a.i=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",U:[{G:"strong",
va:b.text_line_1}]});var m=a.createElement({G:"p",U:[{G:"span",L:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ja:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ja:["iv-button","iv-promo-button"],U:[{G:"span",L:"iv-button-content",va:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&Z3(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.M(a.i,
"iv-click-target");e&&Z3(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",U:[{G:"span",va:b.text_line_1}]}),m=a.createElement({G:"p",U:[{G:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ja:["yt-badge","iv-promo-badge-live"],va:"LIVE NOW"})),g.M(a.i,"iv-click-target"),e&&Z3(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.K.appendChild(a.i);p&&
a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ja:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.i.Ra(a.u,"click",function(r){l4(a,5E3,r)});
c.appendChild(a.u);g.In(a.u,!1);a.context.i.Ra(a.element,"mouseover",a.MS,a);a.context.i.Ra(a.element,"mouseout",a.LS,a);a.context.i.Ra(a.element,"touchend",function(r){l4(a,5E3,r)});
a.B=a.createElement({G:"button",Ja:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.i.Ra(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.HS:a.GS,a);c.appendChild(a.B);g.ms(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},l4=function(a,b,c){c.stopPropagation();
dTa(a);eTa(a,b);a.i.focus()},fTa=function(a){a.isCollapsed||a.S||a.C||(g.M(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},dTa=function(a){a.D.stop();
a.isCollapsed&&(g.os(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.In(a.u,!1),g.In(a.B,!0))},eTa=function(a,b){a.C||(a.C=g.bi(function(){m4(this);
fTa(this)},b,a))},m4=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},gTa=function(a){this.J=a},PSa=function(a,b,c){b&&(c?n4(a,b.map(function(d){return g.$r(d,c)})):n4(a,b))},n4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Gv(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},o4=function(a){g.EM.call(this,a);
var b=this;this.S=!1;this.loadNumber=0;this.I={};this.logger=new gTa(this.player);this.C=new g.LC(this);this.D=this.vl=null;this.events=new g.LC(this);this.K=this.i=null;this.X=[];g.I(this,this.C);this.C.T(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.C.T(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.C.T(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.C.T(this.player,"resize",function(d){b.ea("resize",d)});
this.C.T(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.CQ,this);this.subscribe("resize",this.vA,this);this.player.V().S.subscribe("vast_info_card_add",this.lN,this);g.I(this,this.events);this.Z=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.V({G:"div",Ja:["ytp-player-content","ytp-iv-player-content"]});g.I(this,this.u);g.rM(this.player,this.u.element,4);this.u.hide();this.B=new g.V({G:"div",Ja:["ytp-iv-video-content"]});g.I(this,this.B);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.Mq()&&this.load();var c=this.createElement({G:"style"});(g.Vg("HEAD")[0]||document.body).appendChild(c);g.qe(this,function(){g.mh(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},hTa=function(a){a=a.createElement({G:"div",
Ja:["annotation","annotation-type-custom"]});g.In(a,!1);return a},iTa=function(a,b){b=!b.isCued()&&!g.T(b,1024);
g.nK(a.u,b);g.nK(a.B,b)},jTa=function(a,b,c){a.S=!0;
a.D=g.Du(b,c)},kTa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ma(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(kTa(a,e))}return c},nTa=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.V().S.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.qu(h)&&h.responseXML?h.responseXML:null)&&p4(a,h)}};
g.Tu()&&(d.onFinish=lTa(a,d.onFinish));d.postParams={ic_only:"1"};mTa(d,c);a.S=!0;g.Du(b.Va,d)}}},mTa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Yu&&(a.postParams.ic_coll=b.Yu);b.Hy&&(a.postParams.ic_xml=b.Hy);b.Kx&&(a.postParams.ic_track=b.Kx)},oTa=function(a){var b=new g.V({G:"div"});
g.In(b.element,!1);var c=new c4(a.player,b.element,q4(a));g.I(c,b);b.Ea(a.u.element);c.sx();return c},q4=function(a){if(!a.K){var b=new C3(a);
g.I(a,b);var c=new g.Jl(a);g.I(a,c);a.K=new bTa(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Yd)}return a.K},p4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.ty();if(e){var f=g.sy();f&&g.Gy(void 0,e,f,[g.py(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=kTa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=Q3(f.type,pTa),p=Q3(f.style,qTa),r=vSa(f.data),t=0!==r.length?JSON.parse(r):{};var u=f.action;f=BSa;if(null==u)var x=null;else if(g.La(u)){l=[];for(var y=g.q(u),z=y.next();!z.done;z=y.next()){var D=f(z.value);
D&&l.push(D)}x=l}else{var H=f(u);x=H?[H]:[]}e=m&&n?new CSa(m,n,p,x,t):null}else e=null}catch(ya){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var F=hTa(f),K=null;switch(l.type){case "branding":if(f.player.V().xb)break;f.u.element.appendChild(F);K=new j4(F,q4(f),l);break;case "promotion":g.rM(f.player,F,4),K=new k4(F,q4(f),l)}K&&K.sx();if(f=K)g.I(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=oTa(a),g.I(a,a.i));if("card"===e.type){c=a.i;var W=e&&e.data&&e.data.card_type;
f=e.data;if(W)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,vO:l.teaser_impression,sB:l.teaser_click},F=f.tracking_params||{},K=null,W){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ol:F.card?g.py(F.card):null,bj:F.teaser?g.py(F.teaser):null,Ge:F.icon?g.py(F.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:S3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};f4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ol:F.card?g.py(F.card):
null,bj:F.teaser?g.py(F.teaser):null,Ge:F.icon?g.py(F.icon):null,Hx:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:S3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};f4(c,e);break;case "productListing":f.signin_url&&(K=S3({target:"current",value:f.signin_url}));W=[];for(var J=f.offers||[],Y=0;Y<J.length;Y++)W.push(new HSa(g.Eg(J[Y].merchant),g.Eg(J[Y].price)));e={id:e.id,
timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ol:F.card?g.py(F.card):null,bj:F.teaser?g.py(F.teaser):null,Ge:F.icon?g.py(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Ay:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:
null,url:S3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),bea:K,aea:f.signin_title?f.signin_title:void 0,Zda:f.signin_message?f.signin_message:void 0,offers:W};f4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ol:F.card?g.py(F.card):null,bj:F.teaser?g.py(F.teaser):
null,Ge:F.icon?g.py(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Ay:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:S3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};f4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ol:F.card?g.py(F.card):null,bj:F.teaser?g.py(F.teaser):null,Ge:F.icon?g.py(F.icon):null,Hx:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:S3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},f4(c,e)}}else LSa(a.i,e);c=!0}}c&&(u3(a.player),a.vA())},rTa=function(a,b){var c=!1;
a.i||(a.i=oTa(a),g.I(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(MSa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.yz(b.headerText):"",g.ph(c.jb,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ba=b.trackingParams?g.py(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.py(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Ge=b.icon.infoCardIconRenderer.trackingParams?
g.py(b.icon.infoCardIconRenderer.trackingParams):null,u3(a.player),a.vA())},sTa=function(a,b,c,d,e){if(!a.player.V().xb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new ySa("openUrl","click",new wSa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.yz(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.yz(b.subscriberCountText))):(b.subscriberCountText&&(e=g.yz(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.yz(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.yz(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.yz(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new CSa(c,"branding","branding",f,d);l=hTa(a);a.u.element.appendChild(l);f=new j4(l,q4(a),f);f.sx();g.I(f,f);a.I[c]=f}},lTa=function(a,b){return function(){var c=g.Aa.apply(0,arguments);
a.isDisposed()||a.X.push(g.Ev.Qf(function(){b.apply(null,g.v(c))}))}},tTa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.kM.prototype.Jt=g.ca(17,function(a,b){var c=g.TM(this.vb());c&&c.Jt(a,b)});
var w3={},x3=null;g.Sa(z3,g.xs);g.k=z3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.i)this.progress=0,this.coords=this.u;else if(this.Hc())return!1;y3(this);this.startTime=a=g.Ra();-1==this.i&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.rA();this.zi("play");-1==this.i&&this.zi("resume");this.i=1;var b=g.Pa(this);b in w3||(w3[b]=this);hSa();iSa(this,a);return!0};
g.k.stop=function(a){y3(this);this.i=0;a&&(this.progress=1);jSa(this,this.progress);this.zi("stop");this.Lw()};
g.k.pause=function(){this.Hc()&&(y3(this),this.i=-1,this.zi("pause"))};
g.k.ya=function(){0==this.i||this.stop(!1);this.zi("destroy");z3.le.ya.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.qC=function(){this.zi("animate")};
g.k.zi=function(a){this.dispatchEvent(new kSa(a,this))};
g.Sa(kSa,g.re);g.Sa(A3,z3);A3.prototype.C=g.Ia;A3.prototype.qC=function(){this.C();A3.le.qC.call(this)};
A3.prototype.Lw=function(){this.C();A3.le.Lw.call(this)};
A3.prototype.rA=function(){this.C();A3.le.rA.call(this)};
g.Sa(B3,A3);B3.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(C3,g.G);C3.prototype.Ra=function(a,b,c,d){c=(0,g.E)(c,d||this.u);a=g.pv(a,b,c);this.i.push(a);return a};
C3.prototype.Zz=function(a,b,c,d){c=(0,g.E)(c,d||this.u);a=g.hja(a,b,c);this.i.push(a);return a};
C3.prototype.xc=function(a){g.qv(a);g.Zb(this.i,a)};
C3.prototype.ya=function(){g.qv(this.i);this.i.length=0;g.G.prototype.ya.call(this)};g.w(G3,g.EM);g.k=G3.prototype;g.k.load=function(){g.EM.prototype.load.call(this);if(!H3(this)){var a=g.Psa(this.player.getVideoData());a?(a=F3(a,mSa(this)),I3(this,a,!1)):nSa(this)}};
g.k.unload=function(){I3(this,null);this.B&&(this.B.abort(),this.B=null);g.EM.prototype.unload.call(this)};
g.k.mf=function(a,b){return H3(this)?"loadCustomEndscreenRenderer"===a?(a=F3(b,"new"),I3(this,a),!0):null:null};
g.k.getOptions=function(){return H3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.yb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<uTa.length;f++){var h=Math.abs(b.width-uTa[f]);if(-1===e||d>=h)e=f,d=h}d=vTa[e];this.u&&g.cn(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.rn(e.element,Math.round(h.width*a.width),f);g.kn(e.element,m,n);g.os(e.element,wTa);m=h.left+h.width/2;h=h.top+l/2;g.M(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.os(e.element,vTa);g.M(e.element,d);(e=g.Wg(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.cn(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())P3(this,this.endscreen.impressionUrls),(a=g.ty())&&this.endscreen.visualElement&&g.Hy(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.D[a];g.M(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.M(b,"ytp-ce-shown");P3(this,c.impressionUrls);(b=g.ty())&&g.Hy(b,c.visualElement,void 0);this.player.V().B&&this.player.Oa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.ns(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.ns(b,"ytp-ce-shown");this.player.V().B&&this.player.Oa("endscreenelementhidden",a)}};
g.k.ZW=function(a){var b=this;a.target===window&&(new g.L(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.os(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var uTa=[346,426,470,506,570,640,853,1280,1920],vTa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),wTa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var xSa={n2:"current",t8:"new"};var zSa={CLOSE:"close",M8:"openUrl",SUBSCRIBE:"subscribe"},ASa={m_:"click",CLOSE:"close",P3:"hidden",n$:"rollOut",o$:"rollOver",faa:"shown"};var qTa={oZ:"anchored",oP:"branding",CHANNEL:"channel",m2:"cta",S3:"highlightText",h5:"label",PLAYLIST:"playlist",F9:"popup",raa:"speech",SUBSCRIBE:"subscribe",Jaa:"title",VIDEO:"video",pca:"website"},pTa={oP:"branding",ZZ:"card",H2:"drawer",R3:"highlight",J6:"marker",P9:"promotion",TEXT:"text",Sca:"widget"};g.w(Y3,g.G);g.k=Y3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.rz(a,b,{id:c,namespace:"annotations_module"});d&&this.Sa.set(a,d);e&&this.Va.set(a,e);this.context.J.Gd([a])};
g.k.sx=function(){this.context.u.subscribe("resize",this.Cy,this)};
g.k.rC=function(a,b,c,d,e,f){if(this.eb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.mh(this.element)};
g.k.Cy=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=R3(a);if(f){var h=JSa(f,a.target),l=function(){a.i&&e.context.J.pauseVideo();var m=e.context.videoData.D||!1,n=g.iu(f||"");m&&n&&(n.v||n.list)?e.context.J.Wj(n.v,b,n.list,!1):g.wL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);n4(this.context.logger,c,l,d);ISa(f)||(c=g.ty(),d=b.itct,c&&d&&g.My(c,g.py(d)))}};
g.k.ya=function(){this.Sa.clear();this.Va.clear();g.G.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.I(this,a);return a.element};g.w(c4,Y3);g.k=c4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.sn(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Cy=function(){var a=this.isAvailable();g.In(this.element,a);g.N(this.context.J.getRootNode(),g.gT.IV_DRAWER_ENABLED,a);u3(this.J)};
g.k.destroy=function(){this.J.Jt(!1);try{this.J.getRootNode().removeChild(this.C)}catch(a){}g.Nv(this.Z);g.qv(this.xa);this.La&&this.La.dispose();this.D&&this.D.dispose();Y3.prototype.destroy.call(this)};
g.k.RR=function(){if(this.B){n4(this.context.logger,h4(this).tracking.close);var a=g.ty();a&&this.K&&g.My(a,this.K);b4(this)}};
g.k.dS=function(){g.N(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.wT=function(){var a=g.ty(),b=h4(this);b=b?b.Ge:this.Ge;a&&b&&g.Ky(a,[b])};
g.k.vT=function(){var a=g.ty(),b=h4(this);b=b?b.Ge:this.Ge;a&&b&&g.Ly(a,[b])};
g.k.BQ=function(){var a=h4(this);n4(this.context.logger,a.tracking.vO);var b=g.ty();b&&a&&g.Ky(b,[a.bj,a.Ge])};
g.k.xT=function(){var a=g.ty(),b=h4(this);a&&b&&g.Ly(a,[b.bj])};
g.k.AQ=function(a){var b=h4(this),c=g.ty();this.i?a?(a=this.context.logger,n4(a,b.tracking.sB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.bj&&g.My(c,b.bj)):(a=this.context.logger,n4(a,b.tracking.sB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Ge&&g.My(c,b.Ge)):(a=this.context.logger,n4(a,b.tracking.sB),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Ge&&g.My(c,this.Ge))};g.w(i4,Y3);i4.prototype.sx=function(){Y3.prototype.sx.call(this);XSa(this)};
i4.prototype.show=function(){Y3.prototype.show.call(this);var a=g.ty(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Ky(a,[g.py(b.itct)])};
i4.prototype.hide=function(){Y3.prototype.hide.call(this);var a=g.ty(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.Ly(a,[g.py(b.itct)])};g.w(j4,i4);
j4.prototype.show=function(){if(!this.isActive){i4.prototype.show.call(this);if(!this.K){g.M(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ja:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.In(this.u,!1);var b=this.createElement({G:"div",Ja:["branding-img-container"]});b.appendChild(this.u);this.element.appendChild(b);(b=ESa(this.annotation))&&Z3(this,this.u,b,this.annotation.id,
a.session_data);aTa(this,a);this.K=!0}g.In(this.element,!0);this.isActive=!0;this.u&&YSa(this,this.u)}};
j4.prototype.hide=function(){this.isActive&&(i4.prototype.hide.call(this),g.In(this.element,!1),this.isActive=!1)};
j4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);i4.prototype.destroy.call(this)};g.w(k4,i4);g.k=k4.prototype;g.k.show=function(){this.isActive||(i4.prototype.show.call(this),this.X||(cTa(this),this.X=!0),g.In(this.element,!0),g.bi(function(){g.ns(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,m4(this),dTa(this),eTa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.M(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.rC=function(a,b,c,d,e,f){return this.isCollapsed?!1:i4.prototype.rC.call(this,a,b,c,d,e,f)};
g.k.MS=function(a){this.S=!0;l4(this,500,a)};
g.k.LS=function(){this.S=!1;fTa(this)};
g.k.GS=function(a){a.stopPropagation();this.hide()};
g.k.HS=function(a){a.stopPropagation();m4(this);this.isCollapsed=!0;g.M(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();i4.prototype.destroy.call(this)};g.w(o4,g.EM);g.k=o4.prototype;g.k.mf=function(a,b){if(!tTa(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.P1(b))&&p4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(OSa(this.i,b),u3(this.player)),!0}return null};
g.k.getOptions=function(){return tTa(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Mq=function(){var a=this.player.V(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.FL||a.S.get(b.videoId)||g.jG(b)||g.kG(b)?!0:!1};
g.k.vA=function(){if(this.B){var a=this.player.bb().getVideoContentRect(!0);g.rn(this.B.element,a.width,a.height);g.kn(this.B.element,a.left,a.top)}if(this.i){var b=this.player.xj();a=this.i;b=b.width;g.N(a.C,"iv-drawer-small",426>=b);g.N(a.C,"iv-drawer-big",1280<=b)}};
g.k.CQ=function(a){iTa(this,a.state);g.T(a.state,2)&&(this.Eh()&&this.Bk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Jt(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.qu(h)&&h.responseXML?h.responseXML:null)&&(p4(b,h),g.M(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.EM.prototype.load.call(this);iTa(this,this.player.Ab());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Tu()&&(a=lTa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().S.get(d);f&&mTa(e,f);f=f&&(f.Hy||f.Yu);if(!c.ip||f)c.Va?jTa(this,c.Va,e):(this.vl=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.vl));
g.rM(this.player,this.B.element,4);this.vA();(f=g.jG(c))&&rTa(this,f);(f=g.kG(c))&&f.featuredChannel&&sTa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&(this.vl&&(this.player.removeEventListener("videodatachange",this.vl),this.vl=null),jTa(this,b.Va,a))};
g.k.unload=function(){this.player.Ze("annotations_module");for(var a=g.q(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.K=null;this.i&&(this.i.destroy(),this.i=null,u3(this.player));this.S=!1;this.D&&(this.D.abort(),this.D=null);this.I={};this.u.hide();g.EM.prototype.unload.call(this);this.B.detach();this.vl&&(this.player.removeEventListener("videodatachange",this.vl),this.vl=null)};
g.k.lN=function(a){a===this.player.getVideoData().videoId&&(this.loaded?nTa(this):this.load())};
g.k.Eh=function(){return!!this.i&&this.i.isAvailable()};
g.k.Bk=function(){this.Eh();return!!this.i&&this.i.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Eh();this.i&&(a?c?a4(this.i,c,b):a4(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):b4(this.i))};
g.k.Jt=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ya=function(){this.player.V().S.unsubscribe("vast_info_card_add",this.lN,this);g.ns(this.player.getRootNode(),g.gT.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.Ev.wi(a[b]);this.X.length=0;g.EM.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.I(this,a);return a.element};g.DM("annotations_module",o4);g.DM("creatorendscreen",G3);})(_yt_player);
